#!/bin/bash

if [[ $OSTYPE == darwin* ]]; then
    dir=$(dirname $0)
    path=$PWD${dir:1}
else
    path=$(dirname $(readlink -f $0))
fi

ln -s "$path"/.tmux.conf ~/.tmux.conf
ln -s "$path"/.tmux ~/.tmux
